In [53]:
%matplotlib inline

In [54]:
path = "data/kaggle/dogscats/mine/sample/"
#path = "data/dogscats/sample"

A few basic libraries that we'll need for the initial exercises:

In [55]:
from __future__ import division,print_function

import os, json
from glob import glob
import numpy as np
np.set_printoptions(precision=4, linewidth=100)
from matplotlib import pyplot as plt
import utils; reload(utils)
from utils import plots
from keras.preprocessing import image

In [56]:
# As large as you can, but no larger than 64 is recommended. 
# If you have an older or cheaper GPU, you'll run out of memory, so will have to decrease this.
batch_size=64

In [57]:
# Import our class, and instantiate
from vgg16 import Vgg16

In [58]:
vgg = Vgg16()
# Grab a few images at a time for training and validation.
# NB: They must be in subdirectories named based on their category
batches = vgg.get_batches(path+'train', batch_size=batch_size)
val_batches = vgg.get_batches(path+'valid', batch_size=batch_size*2)


Found 2222 images belonging to 2 classes.
Found 2222 images belonging to 2 classes.


In [59]:
vgg.finetune(batches)
out = vgg.predict(imgs,True)

In [60]:
out

(array([ 0.8976,  0.5243,  0.9989,  0.946 ,  0.5075,  0.9445,  0.9318,  0.8975,  0.9968,  0.9051,
         0.9953,  0.9991,  0.9993,  0.7712,  0.9976,  0.9622,  0.8954,  0.9562,  0.9251,  0.993 ,
         0.9921,  0.999 ,  0.9817,  0.9529,  0.9895,  0.9206,  0.9988,  0.8309,  0.9985,  0.9703,
         0.9997,  0.9622,  0.9902,  0.9997,  0.9784,  0.8995,  0.9973,  0.9785,  0.9991,  0.9966,
         0.9096,  0.5352,  0.8198,  0.7445,  0.9818,  0.9393,  0.5122,  0.9902,  0.8219,  0.7881,
         0.9308,  0.9799,  0.7336,  0.7159,  0.9855,  0.9216,  0.9674,  0.991 ,  0.9816,  0.9996,
         0.9536,  0.505 ,  0.9664,  0.9146], dtype=float32),
 array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]),
 [u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'

In [61]:
vgg.fit(batches, val_batches, nb_epoch=1)
out = vgg.predict(imgs,True)

Epoch 1/1
2222/2222 [==============================] - 120s - loss: 3.5863 - acc: 0.7655 - val_loss: 0.6449 - val_acc: 0.9572


In [62]:
out

(array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1]),
 [u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'tench',

In [63]:
testPath = 'data/kaggle/dogscats/mine/test'
test_batches = vgg.get_batches(testPath, batch_size=batch_size)
imgs,labels = next(test_batches)
out = vgg.predict(imgs,True)

Found 12500 images belonging to 1 classes.


In [64]:
len(out)
out

(array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32),
 array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 0]),
 [u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  

In [65]:
f = open('results.csv','w')
f.write("id,label")
for i in range(len(out[0])):
    f.write('\n{},{}'.format(i+1, out[1][i]))
f.close()